### ISSUE TITLE
Broken on latest canary version

### ISSUE THREAD

**Issue by solonovamax** [Juby210/better-folders#10]
pain.

![image](https://user-images.githubusercontent.com/46940694/118568083-10f43b80-b745-11eb-84e9-ff85230ee88d.png)

(If you can't reproduce, I can give more info)

**Comment by SammCheese** [comment]
Bump

**Comment by Juby210** [comment]
fixed in 4d465b917459e3dbc814ea5bf8d18c478fbc9d96
