### ISSUE TITLE
folder sidebar doesnt work sometimes (actually pretty often)

### ISSUE THREAD

**Issue by mr-miner1** [Juby210/better-folders#11]

**Comment by Juby210** [comment]
Are you using `BDFDB` BD plugin? If yes - it's causing compatibility issues.

**Comment by mr-miner1** [comment]
yea, i am

**Comment by Juby210** [comment]
Closing as it caused by other plugin. (https://github.com/mwittrien/BetterDiscordAddons/blob/805cb0f086ad41de4fcc193330522e71c75eb7cb/Library/0BDFDB.plugin.js#L7792-L7796)
