### ISSUE TITLE
Unreads issue

### ISSUE THREAD

**Issue by SomeAspy** [Juby210/better-folders#2]
red icon saying new mentions doesn't go away until the folder is closed. also, it clips over the server if it reaches the bottom.

**Comment by SheepCommander** [comment]
Will this be fixed one day? It's annoying TF out of me too a year later (hey it's even the same day!)

Not only are there two in both collumns, but it also straight up just doesn't go away even when you scroll down to the bottom where there literally aren't any unreads further down (and it covers up the icon of the servers)

![image](https://user-images.githubusercontent.com/66646514/141939374-24a4d947-9e63-4b71-bc11-29ed088b5ada.png)

![image](https://user-images.githubusercontent.com/66646514/141939412-72bf5368-cbbf-4633-9aba-8f73d5b81752.png)

**Comment by SheepCommander** [comment]
I can't even go back to the [BD version](https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/ServerFolders) which worked just a week ago; either it broke again or the BD Plugin Support happens to not support ServerFolders properly

**Comment by SomeAspy** [comment]
Closing cuz powercord is dead

**Comment by SheepCommander** [comment]
🔥 🔥 🔥 🔥 🔥 🔥
