### ISSUE TITLE
Folders not showing in second bar

### ISSUE THREAD

**Issue by RinLovesYou** [Juby210/better-folders#4]
As the title says, yeah the second row is broken right now.

**Comment by Juby210** [comment]
Can't reproduce, but if you are using BDFDB - BetterFolders isn't compatible with BDFDB.

**Comment by RinLovesYou** [comment]
I don't have BDFDB enabled, but the folders just stay in the normal row

**Comment by RinLovesYou** [comment]
yeah somehow magically fixed itself by completely removing BDFDB, ty
