### ISSUE TITLE
Folder styling issue

### ISSUE THREAD

**Issue by randomdiscorduser** [Juby210/better-folders#6]
When using [Frosted Glass](https://github.com/DiscordStyles/FrostedGlass) there is a styling issue with the bottom of the folders.
![Screen Shot 2021-04-03 at 10 12 01 AM](https://user-images.githubusercontent.com/81717531/113482613-0ca9e280-9465-11eb-9cc5-e7f8a61582e7.png)

**Comment by Juby210** [comment]
(conversation moved to associated PR #5)
