### ISSUE TITLE
Notification bug

### ISSUE THREAD

**Issue by EndergamerHUN** [Juby210/better-folders#7]
When I click a notification to go to a channel, the second column of servers completely disappears, and I need to restart/reload discord. Reopening the folder or any other one does not work.

**Comment by Juby210** [comment]
Are you using BDFDB BD plugin? If yes - it's not supported because it causes a lot of conflicts.

**Comment by EndergamerHUN** [comment]
Oh thanks, didn't realise that was turned on.

Juby210 ***@***.***> ezt írta (időpont: 2021. máj. 7., P,
20:14):
