### ISSUE TITLE
Two red "new notification" buttons

### ISSUE THREAD

**Issue by YeetusBaboon** [Juby210/better-folders#9]
![image](https://user-images.githubusercontent.com/83467783/118017861-b4e08000-b31c-11eb-83c6-4a5d3d04d6c0.png)
As seen above, it has the default discord new notification badge, as well as the one from the plugin.

**Comment by Juby210** [comment]
isn't your issue a duplicate of #2?

**Comment by YeetusBaboon** [comment]
oops- missed that
